server:
  port: 8084

spring:
  application:
    name: contract-service
  config:
    import:
      - classpath:application-common.yml
      - classpath:application-services.yml
  datasource:
    username: ${DATABASE_USER:contract_user}
    password: ${DATABASE_PASSWORD:contract@123}
  jpa:
    properties:
      hibernate:
        default_schema: contract_schema
