smartasset-common:
  image:
    repository: smartasset/orchestrator
    tag: latest
  service:
    type: ClusterIP
    port: 8081
  replicaCount: 1
  envFrom:
    - configMapRef:
        name: smartasset-common-config
    - secretRef:
        name: smartasset-secrets
