apiVersion: v1
kind: ConfigMap
metadata:
  name: smartasset-common-config
  namespace: smartasset
data:
  DATABASE_URL: "jdbc:postgresql://postgres-service:5432/smartasset"
  DATABASE_USER: "user"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "user"
  OTEL_ENDPOINT: "http://otel-collector:4318/v1/traces"
  LOKI_URL: "http://loki-service:3100/loki/api/v1/push"
  # Service URLs
  ASSET_SERVICE_URL: "http://asset-service:8082"
  CUSTOMER_SERVICE_URL: "http://customer-service:8083"
  CONTRACT_SERVICE_URL: "http://contract-service:8084"
  PAYMENT_SERVICE_URL: "http://payment-service:8085"
  DOCUMENT_SERVICE_URL: "http://document-service:8086"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8087"
  MAINTENANCE_SERVICE_URL: "http://maintenance-service:8088"
  BILLING_SERVICE_URL: "http://billing-service:8089"
  AUDIT_SERVICE_URL: "http://audit-service:8090"
  SEARCH_SERVICE_URL: "http://search-service:8091"
  USER_SERVICE_URL: "http://user-service:8092"
  ORCHESTRATOR_URL: "http://orchestrator:8081"
  KEYCLOAK_ISSUER_URI: "http://keycloak-service:8080/realms/smartasset"
  KEYCLOAK_CLIENT_ID: "smartasset-api"
