apiVersion: v1
kind: Secret
metadata:
  name: smartasset-secrets
  namespace: smartasset
type: Opaque
data:
  # Base64 encoded 'password'
  DATABASE_PASSWORD: "cGFzc3dvcmQ="
  RABBITMQ_PASSWORD: "cGFzc3dvcmQ="
  KEYCLOAK_CLIENT_SECRET: ""
