apiVersion: v2
name: customer-service
description: Helm chart for SmartAsset Customer Service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: smartasset-common
    version: 0.1.0
    repository: "file://../smartasset-common"
